name: Generate Sitemap

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  schedule:
    - cron: '0 0 * * 0'  # Additionally, run weekly (every Sunday at 00:00 UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install generate-sitemap
        run: |
          pip install generate-sitemap

      - name: Generate sitemap
        run: |
          generate-sitemap --url https://ifeisachildofgod.github.io/Drug-Me/ --output sitemap.xml

      - name: Commit and push sitemap
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Generate sitemap"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
